# Generated by Django 5.1.4 on 2025-01-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='tg_id',
            new_name='id',
        ),
    ]
