# Generated by Django 5.1.4 on 2025-01-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_rename_tg_id_telegramuser_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telegramuser',
            table=None,
        ),
    ]
