# Generated by Django 5.1.4 on 2025-01-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0004_chathistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'ordering': ['created_at'], 'verbose_name': 'История чата', 'verbose_name_plural': 'Истории чатов'},
        ),
    ]
